// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6yD5-g_Qc-IyQalr5e64NcLCHNEX07c',
    appId: '1:1015989200317:web:c031f9724702c66129ded4',
    messagingSenderId: '1015989200317',
    projectId: 'bao-register',
    authDomain: 'bao-register.firebaseapp.com',
    storageBucket: 'bao-register.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPz_8kc9XCjiVtnBJ6rerCJ4kF1ek1JrY',
    appId: '1:1015989200317:android:7095f01e2b9956a729ded4',
    messagingSenderId: '1015989200317',
    projectId: 'bao-register',
    storageBucket: 'bao-register.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ZjupQlLc7QEoITTw5RbXmCDvI6Rmfjs',
    appId: '1:1015989200317:ios:207c7553659333c429ded4',
    messagingSenderId: '1015989200317',
    projectId: 'bao-register',
    storageBucket: 'bao-register.appspot.com',
    iosBundleId: 'com.example.baoRegister',
  );
}
